# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    # Install uv via asdf (RTD doesn't have uv as a built-in tool)
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    # Fetch tags for hatch-vcs versioning
    - git fetch --tags
    # Install dependencies and build docs
    - uv sync --group docs
    - uv run mkdocs build --strict --site-dir $READTHEDOCS_OUTPUT/html
